language: node_js
sudo: false
node_js:
- 8.6.0
before_install:
- npm config set spin false
- npm install -g coveralls pr-bumper@^3.7.0 ciena-devops@^1.0.0
- "$(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh"
install:
- "$(npm root -g)/pr-bumper/.travis/maybe-install.sh"
script:
- "$(npm root -g)/pr-bumper/.travis/maybe-test.sh"
- ".travis/maybe-bump-version.sh"
after_success:
- ".travis/maybe-publish-coverage.sh"
after_deploy:
- "$(npm root -g)/ciena-devops/scripts/slack/incoming-webhooks/send-message.sh"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  matrix:
  - CXX=g++-4.8
  fast_finish: true
  allow_failures:
  - node: stable
  global:
    secure: laaYXbsBP/iNmP2JpJS+Lvy6F4RYmhsg8fneoS71qXZ+VMXCVq1aXBSyOAPMiP6wA0L8HHwV921IDILeC89oTeYa4xHbiY8C+d/vTMCCIauPaAJTh62DLFamThtKl6GikeIjXjhwHGFVAi3hO+jNyDSnrA0Rxafh/13goRq8iNImeaGgGslkgLIzaeg+T8Yd4lzOEFUoLO9r3N2FR3/MLXEmtemJK93+i/cDwORKfy8iJfnl2XaLiMsXGdjNR0wzjNcvTb4I8E6Wea/bPmV00P/oZMQAI8EgWhjeBMkYwzZdR32G+Qvs7dTvC3I5zHWlQ9Zqhq9X8HDgevD/KAYXT4ObDbeg3bNSDL070WwKa6H+Zk2hxel36krFORx0AKdGmibgccPIfqBuIts3Cpp0+AQuSgdxqI8+GaT45ZAUPYxXb1VoTsppCeGqbdkjCP7zBniF5T5e43rR/tLRsN+jkoZYnXZeULIRcUCv2a1E7dHhwZgCzvgZ2TwAFbu6gmekTsXYt/0OsXLHjNNTPaIyJlGvCdjcxURJqCfx2KdIKiE7/RVzmXqKcehuS1BUabWW5GKA4TBYAfQ5/d5D+PtwWNjap9AZWepdYGkNIQUUIbg20aeVCyA8i+4puC/cpq2T51DHi3zn7wrtVVGxEOgtT6ALEMYLdg/9IEuiNNhbwns=
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: N598rOpXkWfFInRYD7GbA4tFeKmB56c1BLYEOGgsXmUSnGPaDM145iL/HJLB+Qr4kz76/ZNqgHjJqy8mD6a9obzNKW3BkeEAcrAC0/k/3DSHQ3OYUy+Uw8843JKXuF/lBG7jHPJ7JeWuPi4opm/7z1M6V37jnecueomYL2behMqeICPzuqrjS1ExsRH4GevPstAXlFoZ5HvOEip/B5kTTDLki4lEsOvR944dUBnyjLTGTWp2Px8R/NkeiQ8ONj7k6NFpE81yOH1rRlfqDt4Y7eeYgLnaoSaJRL7olWeH6BlJUNLBoxPT23HjJbOhlyiERYTCkLl6xYQ7JS61key0YBoQRW+LCZgr0P5Yk8Ep9+4/Nu0cjysYkakI7YGPmXjur5EThEWa9N1Vug/Ixd1x18IVgzCYLy23DsZYQnrwUn1yh2sDdyPPOBh4dexwWwGNKruH8vpoO8nhtryksTr06XvmW4gHyHpvo7Jx/2L4fyvZTecHBxPfBNuCBb+tQ9Q7ffqdm96MwGGCF6zt1sxJJFo46Ih1kVDb+ASoxAhkkMc/sedNxS5YuG7BdFkRUsyjxNRAETxn2xpi9vL9ChYMp22zXLkLyRuFmNaPLTlSQjUPWp+i6xNFC9zmcWbKRBg4pt09w/Eq0PfjRhF3fhRXw8Rin/oMtKeVnJeqsrh1jvE=
  on:
    all_branches: true
    node: 8.6.0
    tags: true
notifications:
  slack:
    secure: jbOc4tvpPo2cKXJS/U9kZQv/hCswsGmC1SWAQyQFEQNYKCyYZehHZRl4rr1CbhpZhhm9t87EOXUFOlu/js2LN4nkBZSzyFCAsxps+ooG97MEhrys3PQY/9gCRG5c1mhXAwgShEDZI2I7Sqcggubd0Ts87e9N9npsZA3KokwfQFmvf3d3Zx8igTkanAKXUMK4rmhMFxvBoGI6arImfx2MUuZhCm5JVXCoOGfQ0Dyju5EYNERE+s+pvhX+66846j+uOVwsf62JGIgRAX7yNBjBnNM+KHu87G6P0FntNp9M49xMLuBdGyG3zExBbk2XMZosRXPN3oApwGq8UahjFWZ3hu559eT/EYcFXx6hicprNnJH085C9YEHtJ1OiN4BRxY2QTbUXx6vM1IUZc1SN4MWCFP7vWKborzaXA6P/2JIkK756udytuaNC32YuG4RpRRbxspjv3bLbhMzysgPMKqFLj8mHv8m711wgBgqL2lepH7zpOaB2ITwW3JIqkFpqS8g6k+j1Ps7QuoDJ0xfjf2CEM1Lfz2AGWGzPAY0LUnFVF0iPHMyVaA6lmSW4rW9bsbkiY8C3QfNsgSKF4DnhwSLtTP+NB8S+n2CO42Lb42NXrKVavC8Kp1F4qZvPCUtWKlp5kt39AKiNhwtwHwb4QthxStsOE+iSVcEfuU5wAt2vjI=
